# Generated by Django 5.1 on 2024-10-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBookingModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=100)),
                ('HotelRating', models.FloatField()),
                ('HotelPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HotelLocation', models.CharField(max_length=300)),
                ('HotelDescription', models.TextField()),
                ('HotelImage', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('HotelLink', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='Activity1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='Activity2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='Activity3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='Activity4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='Activity5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='LongDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='Nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='star',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tourdestination',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='tourdestination',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_image'),
        ),
    ]
